[package]
name = "game-server"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "ha3-backend-official"
path = "src/bin/ha3-backend-official.rs"

[[bin]]
name = "ha3-backend-local"
path = "src/bin/ha3-backend-local.rs"

[features]
default = []
proto-local = ["proto/proto-local"]

[dependencies]
bytes = { workspace = true }
dotenv = { workspace = true}
itertools = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

boink = { path = "../game-engine/boink" }
hash-cache = { path = "../libs/hash-cache" }
proto = { path = "../proto", default-features = false }

anyhow = "1.0.100"
async-stream = "0.3.6"
dashmap = "6.1.0"
futures-core = "0.3.31"
http = "1.3.1"
jsonwebtoken = "9.3.1"
reqwest = { version = "0.12.23", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
thiserror = "2.0.17"
tokio-stream = { version = "0.1.17", features = ["net"] }
tonic-health = "0.14.2"
tonic-web = "0.14.2"
tower-http = { version = "0.6.6", features = ["cors", "trace"] }
