[workspace]
resolver = "2"
members = ["game-server", "game-engine/boink", "game-engine/boink-ffi", "game-engine/boink-sys", "libs/*", "snapshot-service"]
exclude = ["docker-manager", "gateway-dev", "deploy"]

[workspace.package]
edition = "2024"
rust-version = "1.90"

[workspace.dependencies]
bytes = "1.11"
dotenv = "0.15"
itertools = "0.14"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.48", features = ["full"] }
tonic = { version = "0.14", features = ["tls-native-roots", "tls-ring"] }
prost = "0.14"
prost-types = "0.14"

[profile.dev-release]
inherits = "release"
debug = true
strip = "none"
lto = false
codegen-units = 16
